Client
version: '3'

services:
  postgresql:
    container_name: postgresdb
    ports:
      - "15433:5432"
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: postgres
    networks:
      - rails-net

networks:
  rails-net: